### PR TITLE
Cosmetic changes

### PR DESCRIPTION
**Pull request by Lysxia**

### CODE REVIEW

**Comment by stevana** [comment]
Actually, this seems to break some tests, e.g.:

```
DieHard, Sequential property, `prop_bigJug4`: in most cases, the smallest solution is found

       uncaught exception: ErrorCall (Prelude.read: no parse) (after 1 test)

       failed: *** Failed! Falsifiable (after 49 tests and 8 shrinks): 

       [FillSmall :> Var 8,SmallIntoBig :> Var 11,FillSmall :> Var 12,SmallIntoBig :> Var 20,EmptyBig :> Var 21,SmallIntoBig :> Var 22,FillSmall :> Var 23,SmallIntoBig :> Var 24]
```

The problem is that `Read` instances don't match up with your changes to `Show`.

I think we should leave the show instances as they are, i.e. they should be Haskell expressions in string form, and instead pretty print the history as suggested in #77. I've done this as part of  #147, see `ppHistory`.

**Comment by Lysxia** [comment]
I agree that pretty-printing history seems to be a better approach.

`Show` would be used elsewhere perhaps. Still, the current `Show` doesn't quite produce valid expression either, it would look like:

    [FillSmall (Var 8), ...]

But the first value here is in fact a pair of `FillSmall` (wrapped in some stuff) and `Var 8`.

Perhaps `Read` is the one that also needs a fix?

**Comment by stevana** [comment]
You are right, we should probably keep the `Internal` constructor when showing and change the read instances...

I've created issue #157 for this.

**Comment by Lysxia** [comment]
I'll come back with a better fix.

**Pull request closed without merging**
