### PR TITLE
 Handle missing dot exceptions

### PR DESCRIPTION
**Pull request by kderme**
Signed-off-by: kderme <k.dermenz@gmail.com>
One the the things discussed here https://github.com/advancedtelematic/quickcheck-state-machine/issues/327

### CODE REVIEW

**Comment by stevana** [comment]
Hmm, this still looks wrong:

```
   4-threads:                                                     OK (5.43s)
      +++ OK, failed as expected. Falsified (after 19 tests and 12 shrinks):
      ParallelCommands
        { prefix =
            Commands
              { unCommands =
                  [ Command Create (Created (Reference (Symbolic (Var 0)))) [ Var 0 ]
                  ]
              }
        , suffixes =
            [ [ Commands
                  { unCommands =
                      [ Command (BackAndForth 30 (Reference (Symbolic (Var 0)))) Unit []
                      ]
                  }
              , Commands
                  { unCommands =
                      [ Command
                          (Check (Reference (Symbolic (Var 0)))) (IsNegative False) []
                      ]
                  }
              , Commands
                  { unCommands =
                      [ Command (BackAndForth 58 (Reference (Symbolic (Var 0)))) Unit []
                      ]
                  }
              , Commands
                  { unCommands =
                      [ Command (BackAndForth 40 (Reference (Symbolic (Var 0)))) Unit []
                      ]
                  }
              ]
            ]
        }
      *** Exception running callback: 
      dot: runInteractiveProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
```

**Comment by kderme** [comment]
This was probably a bug of graphviz

**Comment by stevana** [comment]
The Haskell library? Worth reporting?

**Comment by kderme** [comment]
Yes, I submitted a small fix here https://github.com/ivan-m/graphviz/pull/45

**Pull request merged**
